### ISSUE TITLE
ImportError: attempted relative import with no known parent package 

### ISSUE THREAD

**Issue by enricofer** [enricofer/gdrive_provider#4]
@fgianoli

Traceback (most recent call last):
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\__init__.py", line 42, in classFactory
    from .gdrive_provider import Google_Drive_Provider
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_provider.py", line 45, in 
    from .gdrive_layer import progressBar, GoogleDriveLayer
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_layer.py", line 69, in 
    from .services import pack, unpack, google_authorization, service_drive, service_spreadsheet
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\services.py", line 62, in 
    from oauth2client import client, GOOGLE_TOKEN_URI
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\giano\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider-master\extlibs\oauth2client\client.py", line 41, in 
    from gdrive_provider.extlibs.oauth2client import GOOGLE_REVOKE_URI
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_provider.py", line 42, in 
    from . import resources_rc
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: attempted relative import with no known parent package

Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.8.3-Zanzibar Zanzibar, 685d8b15d2

**Comment by enricofer** [comment]
could you try to replace line 42 in gdrive_provider.py 
`import resources_rc` (remove `from .`)

**Comment by fgianoli** [comment]
I have replaced line 42 but I still have this error

ImportError: attempted relative import with no known parent package 
Traceback (most recent call last):
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\__init__.py", line 42, in classFactory
    from .gdrive_provider import Google_Drive_Provider
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_provider.py", line 45, in 
    from .gdrive_layer import progressBar, GoogleDriveLayer
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_layer.py", line 69, in 
    from .services import pack, unpack, google_authorization, service_drive, service_spreadsheet
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\services.py", line 62, in 
    from oauth2client import client, GOOGLE_TOKEN_URI
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\giano\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider-master\extlibs\oauth2client\client.py", line 41, in 
    from gdrive_provider.extlibs.oauth2client import GOOGLE_REVOKE_URI
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_provider.py", line 44, in 
    from .gdrive_provider_dialog import GoogleDriveProviderDialog, accountDialog, comboDialog, importFromIdDialog, internalBrowser, webMapDialog
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: attempted relative import with no known parent package

**Comment by alpterlab** [comment]
Just tried on QGIS | 3.4.10-Madeira and got same problem...

**Comment by enricofer** [comment]
I verified that this issue happen trying to install directly with "import from file" function under manage plugin dialog. For some unknown reasons (the plugin carries with itself many needed external libs) alternative python paths are not handled. Try to manually copy the unzipped folder in the plugins directory https://gis.stackexchange.com/questions/274311/qgis-3-plugin-folder-location and reload QGIS. Then activate the plugin from manage plugins dialog from installed plugins slot

**Comment by alpterlab** [comment]
Impossibile caricare il plugin 'gdrive_provider-master' a causa di un errore chiamando il metodo classFactory() 

ImportError: attempted relative import with no known parent package 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\__init__.py", line 42, in classFactory
    from .gdrive_provider import Google_Drive_Provider
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_provider.py", line 45, in 
    from .gdrive_layer import progressBar, GoogleDriveLayer
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_layer.py", line 69, in 
    from .services import pack, unpack, google_authorization, service_drive, service_spreadsheet
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\services.py", line 62, in 
    from oauth2client import client, GOOGLE_TOKEN_URI
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\info\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider-master\extlibs\oauth2client\client.py", line 41, in 
    from gdrive_provider.extlibs.oauth2client import GOOGLE_REVOKE_URI
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_provider.py", line 44, in 
    from .gdrive_provider_dialog import GoogleDriveProviderDialog, accountDialog, comboDialog, importFromIdDialog, internalBrowser, webMapDialog
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: attempted relative import with no known parent package


Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.4.12-Madeira Madeira, 625767347a 

Percorso Python:
C:/OSGEO4~1/apps/qgis-ltr/./python
C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis-ltr/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\info\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\info\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\info\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider-master\extlibs
C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
C:\Users\info\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\info\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\info\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QuickMultiAttributeEdit3/forms

**Comment by alpterlab** [comment]
> 
> 
> I verified that this issue happen trying to install directly with "import from file" function under manage plugin dialog. For some unknown reasons (the plugin carries with itself many needed external libs) alternative python paths are not handled. Try to manually copy the unzipped folder in the plugins directory https://gis.stackexchange.com/questions/274311/qgis-3-plugin-folder-location and reload QGIS. Then activate the plugin from manage plugins dialog from installed plugins slot

Just did it but it seems the problem...persist.

**Comment by enricofer** [comment]
Could you try to rename plugin folder from gdrive_provider-master to gdrive_provider. I'm not sure that python handle "-" in module names.
Than try to uninstall every other plugin to exclude external libs conflicts.
And finally test in with QGIS 3.8.3

**Comment by alpterlab** [comment]
Finally got it working....  within the python plugin folder with the " gdrive_provider" as folder . 
It does work but sometime the all QGIS get stucked trying to upload files....

**Comment by billjwilliamson** [comment]
Confirm that the fix appears to be the "to rename plugin folder from gdrive_provider-master to gdrive_provider" with a fresh install of the plugin. On QGIS 3.8.1-Zanzibar
